name: Combine Dependabot PRs

on:
  workflow_dispatch:

jobs:
  combine-prs:
    uses: Typeform/.github/.github/workflows/combine-prs.yml@v1
    with:
      runsOn: '[\"ubuntu-latest\"]'
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
